# Generated by Django 6.0.4 on 2026-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='stage',
            field=models.CharField(choices=[('preproject', 'Предпроектная подготовка'), ('design', 'Проектирование'), ('expertise', 'Экспертиза и согласование'), ('preconstruction', 'Подготовка к строительству'), ('construction', 'Строительно-монтажные работы'), ('commissioning', 'Пусконаладочные работы'), ('handover', 'Сдача объекта'), ('operation', 'Эксплуатация')], default='construction', max_length=32),
        ),
    ]
