# Generated by Django 6.0.4 on 2026-04-17 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_filecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfile',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
